### ISSUE TITLE
lowercase slab i (U+0069)

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/alt-hack#11]
Design by @dok42

![i-slab](https://user-images.githubusercontent.com/4249591/32417638-6196c1fc-c22a-11e7-964a-f98b7dcc803a.png)

**Comment by chrissimpkins** [comment]
@dok42 let me know when ready to start on work for a pull request and I will help you through the process.  It is very simple and won't take long to become comfortable with it.

**Comment by tri-nga** [comment]
Thank Chriss
The shape just come from Desjavu Sans Mono, and I've done all the remaining glifs.

**Comment by tri-nga** [comment]
Ok @chrissimpkins 
This is what I've done:
Forked the repo and cloned locally on my PC
Then I did create a branch (u0069) from Github Desktop, I've looked for git bash commands and is easy, but for the fist time I used the desktop app, easier.

So, while on u0069 branch, I added the glif, maintaining the folder structure. 
Here I made a mistake, I think: I deleted the other glif because I thought, "_Well these are on master, arent't they ? I just want to add my own glif"_.

But when I went for a pull request, I had the doubt that the final result of this request, would mean "_delete everything and add u0069 folder_".. 

So I did reset everything, deleted the branch and started from scratch.

Looking ahead for comments from you, to do better for the next glifs.

**Comment by chrissimpkins** [comment]
Looks great @dok42 !  

With all of those changes that you listed, the only change vs. the upstream repository (this one) is the addition of four new `.glif` files in the directory structure that you created in your downstream repository.

You can see this in the diff here https://github.com/source-foundry/alt-hack/pull/12/files 

You can also view the diff for your changes against the upstream by clicking the File Changed tab on the Github UI:

![screenshot at nov 08 09-44-40](https://user-images.githubusercontent.com/4249591/32554980-83435414-c469-11e7-828c-fb7bdda94814.png)

This lets you review every file that is changed vs. the state of the repository here.  You have four new `*.glif` files in your commit which is exactly what we want!

Will hold the review discussion in the pull request thread.  See you over there!

**Comment by chrissimpkins** [comment]
added in https://github.com/source-foundry/alt-hack/commit/4546e588f8c21a54e7c508b47e615c0456bf187b

**Comment by chrissimpkins** [comment]
![slab-reg](https://user-images.githubusercontent.com/4249591/32582506-2d1b2bc6-c4bd-11e7-8cb7-8dbe6c4fc13b.png)

![slab-italic](https://user-images.githubusercontent.com/4249591/32582507-30e71ba2-c4bd-11e7-8f99-b740e7cd0bbd.png)

![slab-bold](https://user-images.githubusercontent.com/4249591/32582514-35851e20-c4bd-11e7-8678-b83284454806.png)

![slab-bolditalic](https://user-images.githubusercontent.com/4249591/32582516-3aecbbac-c4bd-11e7-8b1d-7c2c11c5b886.png)

**Comment by chrissimpkins** [comment]
@dok42 👍 👍 👍  Congratulations!!

![dok42 2017-11-08 19-54-51](https://user-images.githubusercontent.com/4249591/32582836-c29dfeb6-c4be-11e7-9915-a87f9cbf5e28.png)
